### ISSUE TITLE
403ページになる

### ISSUE THREAD

**Issue by baron-tommy** [treetips/schemaspy-mysql#2]
## 現象
docker起動後に、`http://localhost:8081/` を表示した際表示されない (403 Forbidden ページ)
`docker-compose up -d`の後にも表示されない  (403 Forbidden ページ)

## バージョン
```
mysql --version
mysql  Ver 14.14 Distrib 5.7.20, for osx10.11 (x86_64) using  EditLine wrapper
```

## 下記コマンドでターミナルから接続は可能
```
mysql -uroot -hlocalhost -P3306 xymen
```

## IDEの設定
> IDEだと下記で接続できています
```
jdbc:mysql://localhost:3306/xymen
```

## 設定
```
# http://schemaspy.readthedocs.io/en/latest/started.html#configuration
# type of database. Run with -dbhelp for details
schemaspy.t=mysql
# optional path to alternative jdbc drivers.
schemaspy.dp=/app/mysql-connector-java.jar
# database properties: host, port number, name user, password
schemaspy.host=localhost:3306 #ここにポートを付けた方が良い?
schemaspy.port=3306
schemaspy.db=xymen
schemaspy.u=root
# schemaspy.p=
# output dir to save generated files
schemaspy.o=/app/html
# db scheme for which generate diagrams
schemaspy.s=work
```

## ログ
```
tommy@yam-vaio ~/D/schemaspy-mysql> docker-compose up -d
Starting schemaspy_data ... done
Starting schemaspy_core ...
Starting schemaspy_core ... done
tommy@yam-vaio ~/D/schemaspy-mysql> docker-compose run --rm schemaspy
Starting schemaspy_data ... done
3 05, 2018 12:03:59 午後 org.springframework.context.annotation.AnnotationConfigApplicationContext prepareRefresh
情報: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7cd84586: startup date [Mon Mar 05 12:03:59 JST 2018]; root of context hierarchy
Using database properties:
  [schemaspy.jar]/org/schemaspy/types/mysql.properties

Failed to connect to database URL [jdbc:mysql://localhost:3306/xymen]

com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2192)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2225)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:66)
	at org.schemaspy.service.SqlService.connect(SqlService.java:65)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
	at org.schemaspy.Main.main(Main.java:52)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 17 more
12:04:00.408 警告:      Main.main - Connection Failure
org.schemaspy.model.ConnectionFailure: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:92)
	at org.schemaspy.service.SqlService.connect(SqlService.java:65)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:197)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:86)
	at org.schemaspy.Main.main(Main.java:52)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2192)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2225)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:66)
	... 4 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 17 more
```

**Comment by baron-tommy** [comment]
brewのmysqlでインストールした場合うまくいかないようでした
vagrant  + mysql の場合うまくいきました。

もしbrewのmysqlでの解決方法をご存じでしたらお願いします。

**Comment by treetips** [comment]
@baronTommy

> docker起動後に、http://localhost:8081/ を表示した際表示されない (403 Forbidden ページ)

SchemaSpy実行前にブラウズしようとすると、まだ生成していないDB定義書のトップページを表示しようとするため、403になります。

READMEの手順がSchemaSpy実行前にブラウズするようになっていたので、実行後にブラウズするよう更新しました。

SchemaSpyを実行すると、htmlの定義書がnginxのDocumentRootに出力され、定義書が参照可能になります。

> Connection refused

もし接続先のMySQLがDockerコンテナである場合、SchemaSpyからコンテナ上のMySQLへ接続するための設定が別途必要になるかと思います。

例えばAmazonRDSやVagrant上のMySQLの場合は、コンテナ間の通信許可設定（link,expose,subnet設定等）が不要ですので、接続できます。

本リポジトリはコンテナ上のMySQLを対象としておらず、RDSやVagrant上にインストールされたMySQLへの接続を対象としておりました。

**Comment by baron-tommy** [comment]
承知しました

ありがとうございます。
